- name: Set PQCVPN_DD Logo
        run: |
          for size in hdpi mdpi xhdpi xxhdpi xxxhdpi; do
            mkdir -p ui/src/main/res/mipmap-$size
            cp pqc_dd.png ui/src/main/res/mipmap-$size/ic_launcher.png
            cp pqc_dd.png ui/src/main/res/mipmap-$size/ic_launcher_round.png
          done
          find ui/src/main/res/mipmap-* -name "*.xml" -delete
