name: Build PQCVPN_DD APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set PQCVPN_DD Logo
        run: |
          for size in hdpi mdpi xhdpi xxhdpi xxxhdpi; do
            mkdir -p ui/src/main/res/mipmap-$size
            cp pqc_dd.png ui/src/main/res/mipmap-$size/ic_launcher.png
            cp pqc_dd.png ui/src/main/res/mipmap-$size/ic_launcher_round.png
          done

      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -keystore pqcvpn.keystore \
            -alias pqcvpn \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=PQCVPN_DD, OU=PQCVPN, O=PQCVPN_DD, L=IN, S=IN, C=IN" \
            -storepass pqcvpn123 \
            -keypass pqcvpn123

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Sign APK
        run: |
          jarsigner -verbose \
            -sigalg SHA256withRSA \
            -digestalg SHA-256 \
            -keystore pqcvpn.keystore \
            -storepass pqcvpn123 \
            -keypass pqcvpn123 \
            ui/build/outputs/apk/release/ui-release-unsigned.apk \
            pqcvpn
          $ANDROID_HOME/build-tools/$(ls $ANDROID_HOME/build-tools | tail -1)/zipalign \
            -v 4 \
            ui/build/outputs/apk/release/ui-release-unsigned.apk \
            PQCVPN_DD.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PQCVPN_DD
          path: PQCVPN_DD.apk
