- name: Sign APK
        run: |
          keytool -genkeypair -v \
            -keystore pqcvpn.keystore \
            -alias pqcvpn \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=PQCVPN_DD, OU=PQCVPN, O=PQCVPN_DD, L=IN, S=IN, C=IN" \
            -storepass pqcvpn123 \
            -keypass pqcvpn123
          
          BUILD_TOOLS=$ANDROID_HOME/build-tools/$(ls $ANDROID_HOME/build-tools | sort -V | tail -1)
          
          $BUILD_TOOLS/apksigner sign \
            --ks pqcvpn.keystore \
            --ks-pass pass:pqcvpn123 \
            --key-pass pass:pqcvpn123 \
            --ks-key-alias pqcvpn \
            --out PQCVPN_DD.apk \
            ui/build/outputs/apk/release/ui-release-unsigned.apk
